[package]
name = "zesty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
dirs = "4.0.0"
once_cell = "1.17.0"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.5.10"
