[config]

# [[plugins]]
# git = "https://github.com/romkatv/powerlevel10k"
# lazy = 0

[[plugins]]
git = "https://github.com/zdharma-continuum/fast-syntax-highlighting"
lazy = 1

[[plugins]]
git = "https://github.com/tom-doerr/zsh_codex"
lazy = 1

[[plugins]]
git = "https://github.com/zsh-users/zsh-autosuggestions"
lazy = 1

[[plugins]]
git = "https://github.com/zsh-users/zsh-completions"
lazy = 1
